// Supabase Edge Function: verify-razorpay-payment
// Language: Deno / TypeScript
// Purpose: Validates the HMAC-SHA256 signature generated by Razorpay on the server
//          using Web Crypto API and marks the order as paid in the database.

import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

// Helper: Calculate HMAC-SHA256 signature using standard Web Crypto API
async function verifyHmacSha256(secret: string, body: string, signature: string): Promise<boolean> {
  const encoder = new TextEncoder();
  const key = await crypto.subtle.importKey(
    'raw',
    encoder.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );

  const signatureBuffer = await crypto.subtle.sign(
    'HMAC',
    key,
    encoder.encode(body)
  );

  const hashArray = Array.from(new Uint8Array(signatureBuffer));
  const expectedSignatureHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');

  return expectedSignatureHex === signature;
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const {
      order_id,
      razorpay_order_id,
      razorpay_payment_id,
      razorpay_signature,
    } = await req.json();

    if (!order_id || !razorpay_order_id || !razorpay_payment_id || !razorpay_signature) {
      return new Response(
        JSON.stringify({
          error: 'Missing required parameters: order_id, razorpay_order_id, razorpay_payment_id, razorpay_signature',
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const razorpayKeySecret = Deno.env.get('RAZORPAY_KEY_SECRET');
    const supabaseUrl = Deno.env.get('SUPABASE_URL');
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

    if (!razorpayKeySecret) {
      return new Response(
        JSON.stringify({ error: 'RAZORPAY_KEY_SECRET is not configured in Supabase Secrets' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (!supabaseUrl || !supabaseServiceKey) {
      return new Response(
        JSON.stringify({ error: 'Supabase credentials missing in Edge Function environment' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // 1. Verify HMAC SHA-256 Signature
    // Format according to Razorpay docs: `${razorpay_order_id}|${razorpay_payment_id}`
    const payload = `${razorpay_order_id}|${razorpay_payment_id}`;
    const isValidSignature = await verifyHmacSha256(razorpayKeySecret, payload, razorpay_signature);

    const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey);

    if (!isValidSignature) {
      // Mark as failed in DB
      await supabaseAdmin
        .from('orders')
        .update({
          payment_status: 'failed',
          razorpay_order_id,
          razorpay_payment_id,
          updated_at: new Date().toISOString(),
        })
        .eq('id', order_id);

      return new Response(
        JSON.stringify({ error: 'Invalid payment signature. Verification failed.', verified: false }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // 2. Signature is Valid! Mark Order as Paid and Placed
    const { data: updatedOrder, error: updateError } = await supabaseAdmin
      .from('orders')
      .update({
        payment_status: 'paid',
        status: 'placed',
        razorpay_order_id,
        razorpay_payment_id,
        updated_at: new Date().toISOString(),
      })
      .eq('id', order_id)
      .select('*, order_items(*)')
      .single();

    if (updateError) {
      return new Response(
        JSON.stringify({ error: 'Failed to update order status in database', details: updateError }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Optionally clear cart items for this user
    if (updatedOrder.user_id) {
      await supabaseAdmin
        .from('cart_items')
        .delete()
        .eq('user_id', updatedOrder.user_id);
    }

    return new Response(
      JSON.stringify({
        verified: true,
        message: 'Payment verified and order confirmed successfully',
        order: updatedOrder,
      }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (err: any) {
    return new Response(
      JSON.stringify({ error: err.message || 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
